In [3]:
import numpy as np

In [4]:
s = '''0.3	0.3	0.1	0.1	0.1	0.1
0.1	0.3	0.3	0.1	0.1	0.1
0.1	0.1	0.3	0.3	0.1	0.1
0.1	0.1	0.1	0.3	0.3	0.1
0.1	0.1	0.1	0.1	0.3	0.3
0.3	0.1	0.1	0.1	0.1	0.3'''

In [1]:
import os
a = '/Users/parsa/Daneshgah/Arshad/2/NLP/Homeworks/HW2/output/model_02.txt'
os.path.join(os.path.dirname(a), 'log', os.path.basename(a) + '_PO.log')

'/Users/parsa/Daneshgah/Arshad/2/NLP/Homeworks/HW2/output/log/model_02.txt_PO.log'

In [7]:
a = np.fromstring(s, sep=' ')
a

array([0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.3, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.3])

In [13]:
b = a.reshape((3,12))
b

array([[0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.3, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.3]])

In [15]:
np.sum(b, 1)

array([2., 2., 2.])

In [15]:
S = ['A', 'B']
A = np.array(
        [[0.6, 0.4],
         [0, 1]]
    )

dict(zip(S, [dict(zip(s,a)) for s,a in zip(S,A)]))

{'A': {'A': 0.6}, 'B': {'B': 0.0}}

In [6]:
O = ['A', 'B']
v_to_k = {v:k for k,v in enumerate(O)}
v_to_k

{'A': 0, 'B': 1}

In [5]:
S = ['A', 'B']
[S.index(s) for s in S]

[0, 1]

In [22]:
{1: 2}

{1: 2}

In [23]:
{i:3 for i in [2,3]}

{2: 3, 3: 3}

In [3]:
def p(a):
    a[1,2] = 3
    
a = np.zeros((3,3))
p(a)
a

array([[0., 0., 0.],
       [0., 0., 3.],
       [0., 0., 0.]])

In [16]:
a = np.full(5, None)

In [18]:
a[0] is None

True

In [19]:
0.027648000000000002 + 0.13003199999999998

0.15768

In [13]:
a[0] = 5

In [14]:
a

array([5], dtype=object)

In [25]:
O = 'AAB'
O = np.array(list(O))
O

array(['A', 'A', 'B'], dtype='<U1')

In [26]:
O == 'A'

array([ True,  True, False])

In [2]:
import numpy as np 
np.array(2) / np.array(0)

/var/folders/b4/9w931ql57mx2hxsnq2rcgj740000gn/T/ipykernel_10741/2475010960.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.array(2) / np.array(0)


inf

In [4]:
import subprocess
int(subprocess.check_output(['wc', '-l', '/Users/parsa/Daneshgah/Arshad/2/NLP/Homeworks/HW2/hmm_data/seq_model_01.txt']).split()[0])


10000

In [5]:
'adsfdsf'.split('')

ValueError: empty separator

In [2]:
with open('x.txt', 'w+') as f:
    f.write("")

In [10]:
m = '/Users/parsa/Daneshgah/Arshad/2/NLP/Homeworks/HW2/hmm_data/seq_model_01.txt'
with open(m, 'r') as f:
    print(list(f.readline()[:]))

['A', 'C', 'C', 'D', 'D', 'D', 'D', 'F', 'F', 'C', 'C', 'C', 'C', 'B', 'C', 'F', 'F', 'F', 'C', 'C', 'C', 'C', 'C', 'E', 'D', 'A', 'D', 'C', 'C', 'A', 'E', 'F', 'C', 'C', 'C', 'A', 'C', 'D', 'D', 'F', 'F', 'C', 'C', 'D', 'D', 'F', 'F', 'C', 'C', 'D', '\n']


In [1]:
a = np.array([0,1,0])
b = np.array([[3, 4,],
     [6,7]])

NameError: name 'np' is not defined

In [2]:
b[0, a]

NameError: name 'b' is not defined

In [ ]:
import matplotlib.pyplot as plt
fig, axes = plt.subplots()
axes[0].imshow()